name: AntiCooldown
version: 3.6.5-DEV
api-version: 1.13

main: com.yourgamespace.anticooldown.main.AntiCooldown
softdepend:
  - TubeTils

commands:
  anticooldown:
    usage: </command>
    aliases: [ac]