name: AntiCooldown
author: YourGameSpace
website: yourgamespace.com
version: 3.6.5-DEV
api-version: 1.13

main: com.yourgamespace.anticooldown.main.AntiCooldown
softdepend:
  - TubeTils
  - PlaceholderAPI
  - ProtocolLib

permissions:
  anticooldown.settings:
    description: Allows the player to execute commands of the plugin to change settings.
  anticooldown.cooldown:
    description: The player will be affected by cooldown changes.
  anticooldown.combatsounds:
    description: The new combat sounds are deactivated for the player.
  anticooldown.sweepattack:
    description: The SweepAttack particles are deactivated for the player.

commands:
  anticooldown:
    usage: </command>
    aliases: [ac]