name: Create PR
on:
  push:
    branches:
    - "dev/*"
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Pulling ${{ github.ref }} into dev"
        pr_body: ":crown: *An automated PR*"
